[theme]
primaryColor = "#0077CC"          # Garmin Connect blue
backgroundColor = "#F5F5F5"       # Light grey background
secondaryBackgroundColor = "#E0E0E0"  # Slightly darker grey
textColor = "#333333"             # Dark grey for text
font = "sans serif"               # Optional: Choose a font
